language: c

sudo: required
dist: trusty

# Xcode 7.3.1, OS X 10.11
# Xcode 8.3.3, OS X 10.12
#  - xcode7.3

osx_image:
  - xcode7.3

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gettext check bullet dbus fontconfig freetype fribidi gst-plugins-good gstreamer luajit openssl webp libsndfile glib libspectre libraw librsvg poppler lz4; fi

script:
# This errors out. Still needed? Maybe for runtime dbus usage
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew migrate dbus; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p ~/Library/LaunchAgents; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -sfv /usr/local/opt/d-bus/*.plist ~/Library/LaunchAgents; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then launchctl load ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="$(brew --prefix gettext)/bin:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export COPTS="--with-crypto=none --disable-pulseaudio --disable-cxx-bindings"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  ./autogen.sh $COPTS; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  make -j 10; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  make -j 10 examples; fi
