# TODO
# - Create docker images with needed deps installed
# - Create a new docker image after every efl build with efl installed to be used by E, terminology..
# - Create a matrix build with docker images for Ubuntu, Fedora, Arch, openSuse...
# - Create docker build for all extra options
# - Create docker build for wayland options

FROM opensuse:42.2

# Install
RUN zypper --non-interactive update
RUN zypper --non-interactive install -t pattern devel_basis
RUN zypper --non-interactive in -d efl
RUN zypper --non-interactive install gcc-c++ gettext-devel doxygen check libcheck0 check-devel libopenssl-devel systemd-devel libjpeg-devel glib2-devel gstreamer-devel gstreamer-plugins-base-devel luajit-devel freetype2-devel fontconfig-devel fribidi-devel libpng-devel libtiff-devel libcurl-devel libsndfile-devel libX11-devel libXau-devel libXcomposite-devel libXdamage-devel libXdmcp-devel libXext-devel libXfixes-devel libXinerama-devel libXrandr-devel libXrender-devel libXScrnSaver-devel libXtst-devel libXcursor-devel libXp-devel libXi-devel Mesa-libGL-devel giflib-devel libmount-devel libblkid-devel poppler-devel libraw-devel libspectre-devel librsvg2-devel gettext-devel libbullet-devel libudev-devel dbus-1-devel libpulse-devel

# Build
RUN mkdir -p /src/
WORKDIR /src/
COPY . /src/
RUN ./autogen.sh
RUN ulimit -s
RUN ulimit -s 65536
RUN make -j 2
RUN make -j 2 examples
#RUN make -j 10 check
RUN make -j 2 benchmark

#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval $(dbus-launch --sh-syntax --exit-with-session); fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j 10 dist && mkdir tmp && cp efl*.gz tmp/ && cd tmp/ && tar xf efl* && cd efl* && ./configure $COPTS && make -j 10 && make -j 10 ex    amples && make -j 10 benchmark && make -j 10 check && cd ../.. ;fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j 10 distcheck; fi
